# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dP0x2dU0lnc1cG6X1n_8nyg8bJkOtP61
"""

# server.py
import zmq
import time
import json
import joblib
import matplotlib.pyplot as plt
import pandas as pd

model = joblib.load('multiple_reg_model.pth')
robo_labels = joblib.load('robot_id_encoder.pkl')

def predict_next(robot_id, x, y):
    encoded_id = robo_labels.transform([robot_id])[0]
    prediction = model.predict([[encoded_id, x, y]])[0]
    return prediction.tolist()


# zeromq server
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://10.132.172.76:5555")  # server listens on port 5555
print("Server is running...")

start_time = time.time()

while True:
    try:
        if time.time() - start_time > 120:
            print("2 minutes have passed. Closing the server.")
            break

        message = socket.recv_string()
        parts = message.split()
        robot_id = parts[0]
        x = float(parts[1])
        y = float(parts[2])

        print(f"received message: {message}")

        prediction = predict_next(robot_id, x, y)
        response = {'next_x': prediction[0], 'next_y': prediction[1]}
    except Exception as e:
        response = {'error': str(e)}

    socket.send_json(response)

socket.close()
context.term()