# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dP0x2dU0lnc1cG6X1n_8nyg8bJkOtP61
"""

# server.py
import zmq
import json
import joblib
import matplotlib.pyplot as plt
import pandas as pd

model = joblib.load('multiple_reg_model.pth')
robo_labels = joblib.load('robot_id_encoder.pkl')

def predict_next(robot_id, x, y):
    encoded_id = robo_labels.transform([robot_id])[0]
    prediction = model.predict([[encoded_id, x, y]])[0]
    return prediction.tolist()


# zeromq server
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")  # server listens on port 5555
print("server is running...")

while True:
    try:
        message = socket.recv_json()
        robot_id = message['robot_id']
        x = float(message['x'])
        y = float(message['y'])

        print(f"received: {robot_id} at ({x}, {y})")

        prediction = predict_next(robot_id, x, y)
        response = {'next_x': prediction[0], 'next_y': prediction[1]}
    except Exception as e:
        response = {'error': str(e)}

    socket.send_json(response)